import type { LucideIcon } from "lucide-react";
import {
  Archive,
  Bell,
  BookOpen,
  Bookmark,
  Briefcase,
  Calendar,
  Camera,
  CheckCircle2,
  Clock,
  Cloud,
  Coffee,
  File,
  FileText,
  Flag,
  Folder,
  FolderOpen,
  Gift,
  Globe,
  Heart,
  Home,
  Image,
  Inbox,
  Leaf,
  Lightbulb,
  Link2,
  ListTodo,
  Mail,
  MapPin,
  MessageSquare,
  Moon,
  Music,
  Palette,
  PenTool,
  Phone,
  Pin,
  Sparkles,
  Star,
  Sun,
  Tag,
  Target,
  Trash2,
  User,
  Users,
  Video,
} from "lucide-react";

export interface PageIconOption {
  name: string;
  icon: LucideIcon;
  label: string;
}

export const PAGE_ICON_PACK: PageIconOption[] = [
  { name: "file-text", icon: FileText, label: "Document" },
  { name: "file", icon: File, label: "File" },
  { name: "folder", icon: Folder, label: "Folder" },
  { name: "folder-open", icon: FolderOpen, label: "Open folder" },
  { name: "book-open", icon: BookOpen, label: "Book" },
  { name: "bookmark", icon: Bookmark, label: "Bookmark" },
  { name: "pin", icon: Pin, label: "Pin" },
  { name: "tag", icon: Tag, label: "Tag" },
  { name: "link-2", icon: Link2, label: "Link" },
  { name: "globe", icon: Globe, label: "Globe" },
  { name: "home", icon: Home, label: "Home" },
  { name: "inbox", icon: Inbox, label: "Inbox" },
  { name: "archive", icon: Archive, label: "Archive" },
  { name: "trash-2", icon: Trash2, label: "Trash" },
  { name: "star", icon: Star, label: "Star" },
  { name: "briefcase", icon: Briefcase, label: "Briefcase" },
  { name: "calendar", icon: Calendar, label: "Calendar" },
  { name: "clock", icon: Clock, label: "Clock" },
  { name: "check-circle-2", icon: CheckCircle2, label: "Done" },
  { name: "list-todo", icon: ListTodo, label: "Tasks" },
  { name: "target", icon: Target, label: "Target" },
  { name: "flag", icon: Flag, label: "Flag" },
  { name: "map-pin", icon: MapPin, label: "Location" },
  { name: "users", icon: Users, label: "Team" },
  { name: "user", icon: User, label: "Person" },
  { name: "message-square", icon: MessageSquare, label: "Chat" },
  { name: "mail", icon: Mail, label: "Mail" },
  { name: "phone", icon: Phone, label: "Phone" },
  { name: "bell", icon: Bell, label: "Bell" },
  { name: "image", icon: Image, label: "Image" },
  { name: "camera", icon: Camera, label: "Camera" },
  { name: "video", icon: Video, label: "Video" },
  { name: "music", icon: Music, label: "Music" },
  { name: "palette", icon: Palette, label: "Palette" },
  { name: "pen-tool", icon: PenTool, label: "Design" },
  { name: "lightbulb", icon: Lightbulb, label: "Idea" },
  { name: "sparkles", icon: Sparkles, label: "Sparkles" },
  { name: "heart", icon: Heart, label: "Heart" },
  { name: "gift", icon: Gift, label: "Gift" },
  { name: "coffee", icon: Coffee, label: "Coffee" },
  { name: "sun", icon: Sun, label: "Sun" },
  { name: "moon", icon: Moon, label: "Moon" },
  { name: "cloud", icon: Cloud, label: "Cloud" },
  { name: "leaf", icon: Leaf, label: "Leaf" },
];

export const LUCIDE_ICON_MAP = Object.fromEntries(
  PAGE_ICON_PACK.map(({ name, icon }) => [name, icon])
) as Record<string, LucideIcon>;
