import type { LucideIcon } from "lucide-react";
import {
  Activity,
  AlarmClock,
  Archive,
  Award,
  BarChart3,
  Bell,
  Bike,
  Binary,
  Blocks,
  BookOpen,
  Bookmark,
  Bot,
  Box,
  Brain,
  Briefcase,
  Brush,
  Bug,
  Building2,
  Calculator,
  Calendar,
  Camera,
  Car,
  CheckCircle2,
  Circle,
  ClipboardList,
  Clock,
  Cloud,
  Code2,
  Coffee,
  Coins,
  Compass,
  Contact,
  Cpu,
  Crown,
  Database,
  Diamond,
  Dog,
  Dumbbell,
  Factory,
  File,
  FileCode,
  FileSpreadsheet,
  FileText,
  Film,
  Flag,
  Flame,
  FlaskConical,
  Flower2,
  Folder,
  FolderOpen,
  Gamepad2,
  Gem,
  Gift,
  GitBranch,
  Globe,
  GraduationCap,
  Hammer,
  HardDrive,
  Headphones,
  Heart,
  Hexagon,
  History,
  Home,
  IceCream,
  Image,
  Inbox,
  Key,
  Keyboard,
  Landmark,
  Languages,
  Laptop,
  LayoutGrid,
  Leaf,
  Library,
  Lightbulb,
  Link2,
  ListTodo,
  Lock,
  Mail,
  MapPin,
  Megaphone,
  MessageCircle,
  MessageSquare,
  Microscope,
  Milestone,
  Monitor,
  Moon,
  Mountain,
  Music,
  Newspaper,
  Notebook,
  Package,
  Paintbrush,
  Palette,
  PartyPopper,
  PawPrint,
  PenTool,
  Pencil,
  Phone,
  PieChart,
  Pin,
  Plane,
  Plug,
  Podcast,
  Puzzle,
  Receipt,
  Rocket,
  Rss,
  Ruler,
  Scale,
  School,
  Scissors,
  Search,
  Send,
  Server,
  Settings,
  Share2,
  Shield,
  Ship,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Snowflake,
  Sparkles,
  Sprout,
  Square,
  Star,
  Stethoscope,
  Store,
  StickyNote,
  Sun,
  Tag,
  Target,
  Terminal,
  Ticket,
  Timer,
  Train,
  Trash2,
  TreeDeciduous,
  TreePine,
  TrendingUp,
  Trophy,
  Truck,
  Umbrella,
  User,
  Users,
  Utensils,
  Video,
  Wallet,
  Wand2,
  Waves,
  Wifi,
  Wind,
  Wine,
  Wrench,
  Zap,
} from "lucide-react";

export interface PageIconOption {
  name: string;
  icon: LucideIcon;
  label: string;
  keywords?: string;
}

export const PAGE_ICON_PACK: PageIconOption[] = [
  // Documents & files
  { name: "file-text", icon: FileText, label: "Document", keywords: "page note doc" },
  { name: "file", icon: File, label: "File", keywords: "generic" },
  { name: "file-code", icon: FileCode, label: "Code file", keywords: "dev programming" },
  { name: "file-spreadsheet", icon: FileSpreadsheet, label: "Spreadsheet", keywords: "excel sheet data" },
  { name: "notebook", icon: Notebook, label: "Notebook", keywords: "journal notes" },
  { name: "sticky-note", icon: StickyNote, label: "Sticky note", keywords: "memo" },
  { name: "newspaper", icon: Newspaper, label: "News", keywords: "article blog" },
  { name: "book-open", icon: BookOpen, label: "Book", keywords: "read library" },
  { name: "library", icon: Library, label: "Library", keywords: "books collection" },
  { name: "clipboard-list", icon: ClipboardList, label: "Checklist", keywords: "list clipboard" },

  // Folders & organization
  { name: "folder", icon: Folder, label: "Folder", keywords: "directory" },
  { name: "folder-open", icon: FolderOpen, label: "Open folder", keywords: "directory" },
  { name: "archive", icon: Archive, label: "Archive", keywords: "storage old" },
  { name: "inbox", icon: Inbox, label: "Inbox", keywords: "mail receive" },
  { name: "trash-2", icon: Trash2, label: "Trash", keywords: "delete bin" },
  { name: "bookmark", icon: Bookmark, label: "Bookmark", keywords: "save mark" },
  { name: "pin", icon: Pin, label: "Pin", keywords: "fixed important" },
  { name: "tag", icon: Tag, label: "Tag", keywords: "label category" },
  { name: "blocks", icon: Blocks, label: "Blocks", keywords: "modules sections" },
  { name: "layout-grid", icon: LayoutGrid, label: "Grid", keywords: "layout board" },

  // Work & business
  { name: "briefcase", icon: Briefcase, label: "Work", keywords: "business job office" },
  { name: "building-2", icon: Building2, label: "Building", keywords: "office company" },
  { name: "landmark", icon: Landmark, label: "Institution", keywords: "bank government" },
  { name: "store", icon: Store, label: "Store", keywords: "shop retail" },
  { name: "factory", icon: Factory, label: "Factory", keywords: "manufacturing industry" },
  { name: "package", icon: Package, label: "Package", keywords: "box delivery product" },
  { name: "wallet", icon: Wallet, label: "Wallet", keywords: "money finance" },
  { name: "coins", icon: Coins, label: "Coins", keywords: "money finance crypto" },
  { name: "receipt", icon: Receipt, label: "Receipt", keywords: "invoice billing ticket" },
  { name: "ticket", icon: Ticket, label: "Ticket", keywords: "event pass admission" },
  { name: "scale", icon: Scale, label: "Legal", keywords: "law justice balance" },
  { name: "calculator", icon: Calculator, label: "Calculator", keywords: "math numbers" },
  { name: "bar-chart-3", icon: BarChart3, label: "Bar chart", keywords: "analytics stats" },
  { name: "pie-chart", icon: PieChart, label: "Pie chart", keywords: "analytics stats" },
  { name: "trending-up", icon: TrendingUp, label: "Growth", keywords: "analytics trend" },

  // Productivity
  { name: "calendar", icon: Calendar, label: "Calendar", keywords: "date schedule" },
  { name: "clock", icon: Clock, label: "Clock", keywords: "time schedule" },
  { name: "alarm-clock", icon: AlarmClock, label: "Alarm", keywords: "reminder wake" },
  { name: "timer", icon: Timer, label: "Timer", keywords: "countdown stopwatch" },
  { name: "history", icon: History, label: "History", keywords: "past timeline" },
  { name: "check-circle-2", icon: CheckCircle2, label: "Done", keywords: "complete success" },
  { name: "list-todo", icon: ListTodo, label: "Tasks", keywords: "todo checklist" },
  { name: "target", icon: Target, label: "Target", keywords: "goal focus aim" },
  { name: "flag", icon: Flag, label: "Flag", keywords: "milestone priority" },
  { name: "milestone", icon: Milestone, label: "Milestone", keywords: "goal checkpoint roadmap" },
  { name: "search", icon: Search, label: "Search", keywords: "find lookup" },
  { name: "settings", icon: Settings, label: "Settings", keywords: "config preferences" },

  // Communication
  { name: "mail", icon: Mail, label: "Mail", keywords: "email message" },
  { name: "message-square", icon: MessageSquare, label: "Chat", keywords: "message talk" },
  { name: "message-circle", icon: MessageCircle, label: "Comment", keywords: "chat bubble" },
  { name: "phone", icon: Phone, label: "Phone", keywords: "call contact" },
  { name: "send", icon: Send, label: "Send", keywords: "share deliver" },
  { name: "share-2", icon: Share2, label: "Share", keywords: "social distribute" },
  { name: "megaphone", icon: Megaphone, label: "Announce", keywords: "marketing broadcast" },
  { name: "bell", icon: Bell, label: "Bell", keywords: "notification alert" },
  { name: "contact", icon: Contact, label: "Contact", keywords: "person card" },
  { name: "rss", icon: Rss, label: "Feed", keywords: "rss subscribe" },
  { name: "user", icon: User, label: "Person", keywords: "profile account" },
  { name: "users", icon: Users, label: "Team", keywords: "group people" },
  { name: "graduation-cap", icon: GraduationCap, label: "Education", keywords: "school university" },
  { name: "school", icon: School, label: "School", keywords: "class learning" },
  { name: "crown", icon: Crown, label: "Premium", keywords: "vip leader" },
  { name: "award", icon: Award, label: "Award", keywords: "achievement badge" },
  { name: "trophy", icon: Trophy, label: "Trophy", keywords: "win success" },
  { name: "party-popper", icon: PartyPopper, label: "Celebrate", keywords: "party event" },

  // Places & travel
  { name: "home", icon: Home, label: "Home", keywords: "house workspace" },
  { name: "globe", icon: Globe, label: "Globe", keywords: "world web international" },
  { name: "map-pin", icon: MapPin, label: "Location", keywords: "place map address" },
  { name: "compass", icon: Compass, label: "Compass", keywords: "direction explore" },
  { name: "plane", icon: Plane, label: "Travel", keywords: "flight trip vacation" },
  { name: "car", icon: Car, label: "Car", keywords: "drive transport" },
  { name: "train", icon: Train, label: "Train", keywords: "rail commute transit" },
  { name: "ship", icon: Ship, label: "Ship", keywords: "boat cruise ocean" },
  { name: "truck", icon: Truck, label: "Truck", keywords: "delivery logistics" },
  { name: "mountain", icon: Mountain, label: "Mountain", keywords: "outdoors hike nature" },
  { name: "waves", icon: Waves, label: "Ocean", keywords: "beach water sea" },
  { name: "umbrella", icon: Umbrella, label: "Umbrella", keywords: "rain weather" },

  // Creative & media
  { name: "image", icon: Image, label: "Image", keywords: "photo picture gallery" },
  { name: "camera", icon: Camera, label: "Camera", keywords: "photo shoot" },
  { name: "video", icon: Video, label: "Video", keywords: "film movie record" },
  { name: "film", icon: Film, label: "Film", keywords: "cinema movie" },
  { name: "music", icon: Music, label: "Music", keywords: "audio song sound" },
  { name: "headphones", icon: Headphones, label: "Headphones", keywords: "audio listen podcast" },
  { name: "podcast", icon: Podcast, label: "Podcast", keywords: "audio show mic" },
  { name: "palette", icon: Palette, label: "Palette", keywords: "color art design" },
  { name: "paintbrush", icon: Paintbrush, label: "Paint", keywords: "art brush design" },
  { name: "pen-tool", icon: PenTool, label: "Design", keywords: "vector draw" },
  { name: "pencil", icon: Pencil, label: "Pencil", keywords: "write edit draft" },
  { name: "brush", icon: Brush, label: "Brush", keywords: "paint art" },
  { name: "scissors", icon: Scissors, label: "Scissors", keywords: "cut craft" },
  { name: "ruler", icon: Ruler, label: "Ruler", keywords: "measure design" },
  { name: "wand-2", icon: Wand2, label: "Magic", keywords: "ai effects sparkle" },

  // Tech & development
  { name: "code-2", icon: Code2, label: "Code", keywords: "dev programming software" },
  { name: "terminal", icon: Terminal, label: "Terminal", keywords: "cli shell command" },
  { name: "binary", icon: Binary, label: "Binary", keywords: "data bits dev" },
  { name: "database", icon: Database, label: "Database", keywords: "data storage sql" },
  { name: "server", icon: Server, label: "Server", keywords: "storage backend host" },
  { name: "hard-drive", icon: HardDrive, label: "Hard drive", keywords: "storage disk" },
  { name: "cpu", icon: Cpu, label: "CPU", keywords: "chip processor hardware" },
  { name: "monitor", icon: Monitor, label: "Monitor", keywords: "screen desktop computer" },
  { name: "laptop", icon: Laptop, label: "Laptop", keywords: "computer device" },
  { name: "smartphone", icon: Smartphone, label: "Phone", keywords: "mobile device" },
  { name: "keyboard", icon: Keyboard, label: "Keyboard", keywords: "typing input" },
  { name: "plug", icon: Plug, label: "Plugin", keywords: "integration connect" },
  { name: "wifi", icon: Wifi, label: "Wi-Fi", keywords: "network internet" },
  { name: "git-branch", icon: GitBranch, label: "Git", keywords: "branch version dev" },
  { name: "bug", icon: Bug, label: "Bug", keywords: "issue debug error" },
  { name: "bot", icon: Bot, label: "Bot", keywords: "ai automation robot" },
  { name: "gamepad-2", icon: Gamepad2, label: "Games", keywords: "gaming play" },

  // Ideas & learning
  { name: "lightbulb", icon: Lightbulb, label: "Idea", keywords: "insight brainstorm" },
  { name: "brain", icon: Brain, label: "Brain", keywords: "mind thinking knowledge" },
  { name: "microscope", icon: Microscope, label: "Research", keywords: "science lab study" },
  { name: "flask-conical", icon: FlaskConical, label: "Experiment", keywords: "science lab test" },
  { name: "puzzle", icon: Puzzle, label: "Puzzle", keywords: "problem solve piece" },
  { name: "languages", icon: Languages, label: "Languages", keywords: "translate i18n" },
  { name: "link-2", icon: Link2, label: "Link", keywords: "url reference" },

  // Health & wellness
  { name: "activity", icon: Activity, label: "Activity", keywords: "fitness health pulse" },
  { name: "dumbbell", icon: Dumbbell, label: "Fitness", keywords: "gym workout exercise" },
  { name: "stethoscope", icon: Stethoscope, label: "Health", keywords: "medical doctor" },
  { name: "heart", icon: Heart, label: "Heart", keywords: "love favorite health" },

  // Nature & weather
  { name: "leaf", icon: Leaf, label: "Leaf", keywords: "nature plant eco" },
  { name: "sprout", icon: Sprout, label: "Sprout", keywords: "grow plant seed" },
  { name: "tree-deciduous", icon: TreeDeciduous, label: "Tree", keywords: "nature forest" },
  { name: "tree-pine", icon: TreePine, label: "Pine", keywords: "nature forest christmas" },
  { name: "flower-2", icon: Flower2, label: "Flower", keywords: "nature garden bloom" },
  { name: "sun", icon: Sun, label: "Sun", keywords: "day weather bright" },
  { name: "moon", icon: Moon, label: "Moon", keywords: "night dark sleep" },
  { name: "cloud", icon: Cloud, label: "Cloud", keywords: "weather sky storage" },
  { name: "snowflake", icon: Snowflake, label: "Snow", keywords: "winter cold" },
  { name: "wind", icon: Wind, label: "Wind", keywords: "weather breeze" },
  { name: "flame", icon: Flame, label: "Flame", keywords: "fire hot energy" },
  { name: "zap", icon: Zap, label: "Energy", keywords: "lightning power fast" },

  // Lifestyle
  { name: "coffee", icon: Coffee, label: "Coffee", keywords: "cafe drink morning" },
  { name: "utensils", icon: Utensils, label: "Food", keywords: "restaurant meal dining" },
  { name: "wine", icon: Wine, label: "Wine", keywords: "drink bar" },
  { name: "ice-cream", icon: IceCream, label: "Dessert", keywords: "sweet treat" },
  { name: "gift", icon: Gift, label: "Gift", keywords: "present birthday" },
  { name: "shopping-bag", icon: ShoppingBag, label: "Shopping", keywords: "buy store retail" },
  { name: "shopping-cart", icon: ShoppingCart, label: "Cart", keywords: "buy ecommerce" },
  { name: "dog", icon: Dog, label: "Dog", keywords: "pet animal" },
  { name: "paw-print", icon: PawPrint, label: "Pet", keywords: "animal paw" },
  { name: "bike", icon: Bike, label: "Bike", keywords: "cycle sport commute" },

  // Symbols & misc
  { name: "star", icon: Star, label: "Star", keywords: "favorite featured" },
  { name: "sparkles", icon: Sparkles, label: "Sparkles", keywords: "new magic shine" },
  { name: "gem", icon: Gem, label: "Gem", keywords: "diamond precious value" },
  { name: "diamond", icon: Diamond, label: "Diamond", keywords: "precious luxury" },
  { name: "rocket", icon: Rocket, label: "Rocket", keywords: "launch startup space" },
  { name: "shield", icon: Shield, label: "Shield", keywords: "security protect safe" },
  { name: "lock", icon: Lock, label: "Lock", keywords: "secure private password" },
  { name: "key", icon: Key, label: "Key", keywords: "access unlock" },
  { name: "hammer", icon: Hammer, label: "Build", keywords: "tools construct fix" },
  { name: "wrench", icon: Wrench, label: "Tools", keywords: "fix settings repair" },
  { name: "box", icon: Box, label: "Box", keywords: "container package" },
  { name: "circle", icon: Circle, label: "Circle", keywords: "shape dot" },
  { name: "square", icon: Square, label: "Square", keywords: "shape block" },
  { name: "hexagon", icon: Hexagon, label: "Hexagon", keywords: "shape honeycomb" },
];

export const LUCIDE_ICON_MAP = Object.fromEntries(
  PAGE_ICON_PACK.map(({ name, icon }) => [name, icon])
) as Record<string, LucideIcon>;
